plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.0'
}

group = 'dev.despical'
version = '3.2.2'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.12.3'
    compileOnly 'org.projectlombok:lombok:1.18.46'

    implementation('dev.despical:commons:2.1.2') {
        exclude group: 'org.slf4j'
    }

    implementation 'dev.despical:command-framework:1.6.5'
    implementation 'dev.despical:inventory-framework:2.4.7'
    implementation 'dev.despical:file-items:1.2.5'
    implementation 'com.github.Despical:ParticleLib:1.0.9'
    implementation 'org.bstats:bstats-bukkit:3.2.1'
    implementation 'fr.skytasul:glowingentities:1.4.10'

    annotationProcessor 'org.projectlombok:lombok:1.18.40'
}

tasks.processResources {
    def props = [version: version]
    inputs.properties props

    filteringCharset = 'UTF-8'

    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.jar {
    enabled = false
}

tasks.shadowJar {
    minimize()

    relocate 'dev.despical.commons', 'dev.despical.kotl.lib.commons'
    relocate 'dev.despical.commandframework', 'dev.despical.kotl.lib.commandframework'
    relocate 'dev.despical.inventoryframework', 'dev.despical.kotl.lib.inventoryframework'
    relocate 'dev.despical.fileitems', 'dev.despical.kotl.lib.fileitems'
    relocate 'dev.despical.particle', 'dev.despical.kotl.lib.particlelib'
    relocate 'org.bstats', 'dev.despical.kotl.lib.bstats'
    relocate 'fr.skytasul.glowingentities', 'dev.despical.kotl.lib.glowingentities'

    exclude 'META-INF/**'
    exclude 'fonts/**'

    archiveFileName = "king-of-the-ladder-${version}.jar"

    def hostName = InetAddress.getLocalHost().getHostName()
    if (hostName == "DESKTOP-RD26J35") {
        destinationDirectory = file("C:/Users/berke/OneDrive/Masaüstü/Paper 26.1.2/plugins")
    }
}
