# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                             #
#                     King of the Ladder                      #
#                          Despical                           #
#                                                             #
#            https://www.buymeacoffee.com/despical            #
#                                                             #
#            Donations are really appreciated! <3             #
#                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# If you want to translate for us check out: https://github.com/Despical/LocaleStorage#locale-storage

# Available locales:
#    default - English
#    de - Deutsche
#    tr - Türkçe
locale: default

Arena-Schedulers:
  # Type 1: Creates a general task that loops all arenas and players to check
  # if they are inside any arena, if they are they'll be put in the game.
  #
  # Type 2: Creates tasks for every arena which means every arena will look for
  # all online players in their own task.
  #
  # Type 3 (Slowest for big networks): Registers a PlayerMoveEvent and checks in
  # the event if player is inside any arena.
  Type: 1

  # How many ticks should we wait to lookup for players to put in arenas
  Interval: 2

  # Should we search for arenas asynchronously?
  # In most cases events firing in main thread so async won't work for Type 3.
  Async: false

King-Settings:
  # Should we allow players to become king in a row?
  Become-King-In-A-Row: false

  # Should we prevent players to become king again without a delay?
  Cooldown: 5

  # The permission to override king cooldown.
  Cooldown-Override-Perm: ""

  # Should we apply an action bar message that displays current cooldown of player?
  Cooldown-Bar: true

  # Should we apply the cooldown to the king when there is only one player in the arena?
  Cooldown-When-Alone: false

  Remove-Cooldown-On:
    # Should we remove player's becoming king cooldown when they join an arena, if they have?
    Join: false
    # Should we remove player's becoming king cooldown when they leave an arena, if they have?
    Leave: false

# Enable boss bar support?
Boss-Bar-Enabled: true

# Enable scoreboard support?
Scoreboard-Enabled: true

# Enable this option when you're using MySQL, otherwise it won't work.
# Be careful when changing this because there is NO migrator between
# flat file and MySQL for player stats.
Database-Enabled: false

# Enable Inventory Manager for your games? (Very useful feature for MULTI ARENA)
# This saves inventory of players and restores it after player leaves arena.
# Saved elements: max health, health, food, experience, full inventory, armor contents, and more.
Inventory-Manager:
  Enabled: true
  # Usable attributes:
  #  game-mode, hunger, exp, level
  #  health, max-health, health-scale
  #  saturation, allow-flight, fire-ticks
  Do-Not-Restore:
    - "max-health"
    - "health-scale"

# Should we clear player's inventory on joining and leaving the game area?
# Also disable InventoryManager option before enabling this option.
Clear-Inventory: true

# Should we clear player's active potion effects when player join the arena?
Clear-Effects: true

# Should in game chat format be enabled?
# You can edit the formatting in messages.yml
Chat-Format-Enabled: true

# Should we disable all chat related stuff?
# It will disable the separated chat.
Disable-Separate-Chat: false

# Should players get fall damage?
Disable-Fall-Damage: true

# Which game mode should we set for players when they enter the arena?
Game-Mode: SURVIVAL

# Show a cuboid particle effect around the arena corners.
Arena-Outlines:
  Step: .4
  Particle: FLAME

# The delay between hitting players. ONLY EFFECTED in Minecraft 1.9+
Hit-Cooldown-Delay: 16

# Commands which can be used in game, remove all of them to disable
Whitelisted-Commands:
  - me
  - help

# Should we spawn some cool fireworks around the game area when someone becomes king?
Fireworks-On-New-King: true

# Should we block every not King of the Ladder associated commands in game?
Block-Commands: true

# Should we enable damage?
# This option may be helpful if you enabled the kits.
Damage-Enabled: true

# When players click these blocks should we remove them from the game?
Death-Blocks-Enabled: true

# Blocks which you should not click in game, remove all of them to disable.
# If player interacts with a death block they will be kicked from the game.
Death-Blocks:
  - BEDROCK
  - GLASS

# When player enters the game area should we notify players?
Join-Notify: true

# When player leaves the game area should we notify players?
Leave-Notify: true

# Should we check for updates on plugin start/after admin join?
Update-Notifier-Enabled: true

# No way! You've reached the end! But... where's the dragon!?