name: KOTL
main: me.despical.kotl.Main
author: Despical
version: ${project.version}

api-version: 1.13
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - WorldGuard

permissions:
  kotl.admin.*:
    default: op
    children:
      kotl.admin: true
      kotl.admin.create: true
      kotl.admin.delete: true
      kotl.admin.edit: true
      kotl.admin.list: true
      kotl.admin.help: true
      kotl.admin.reload: true
      kotl.admin.kick: true
      kotl.command.override: true
      kotl.admin.cooldown: true
